#! /usr/bin/env python
# encoding: utf-8

#from waflib.Configure import conf
import glob, os

sources_with_main=[
    "main.cpp"]

def build(bld):
    """..."""
    print(
        "building at srcpath",
        bld.path.srcpath())
    cpp_files={
        file.split("/")[-1]
        for file in glob.glob(
                bld.path.abspath() + "/*.cpp")}
    INCLUDES=\
		["../../" + x for x in bld.env.INCLUDES_REL] + bld.env.INCLUDES_ABS
    bld.objects(
        source=cpp_files.difference(
            sources_with_main),
        target="tutorial",
        includes=INCLUDES,
        cxxflags=bld.env.CXXFLAGS)
    #uncomment region to create a static library
    # bld.stlib(
    #     source = cpp_files,
    #     target = "tutorial",
    #     cxxflags = bld.env.CXXFLAGS,
    #     includes = includes,
    #     lib = bld.env.LDFLAGS_N)
    bld.env.append_unique(
        "targets",
        os.path.join(
            bld.path.srcpath(),
            "tutorial"))
    bld.program(
        source="main.cpp",
        use=["FS"],
        target="tutorial",
        stlib=bld.env.STLIB, #static lib - needed if not default
        cxxflags=bld.env.CXXFLAGS,
        includes=INCLUDES,
        lib=bld.env.LDFLAGS_N)

